---

include:
  - project: 'stas/gitlab-ci/python-build'
    ref: v1beta1
    file: 'python-package.yml'

variables:
  PYTHON_VERSIONS: "/(3.7)|(3.8)/"
  PYTHON_PUBLISH_VERSION: "3.8"
  PKG_NAME: "cimsparql"
  PROJECT_NAME: "cimsparql"
  APT_INSTALL_PACKAGES: "librdf0"
  BUILD_DOCS: "true"
