image:
  name: "gitlab-registry.statnett.no/abot/opf:latest"

stages:
  - tests
  - deploy

run_tests:
  stage: tests
  script:
    - tox
  artifacts:
    paths:
      - coverage.xml
    expire_in: 1 day

sonar_update:
  stage: deploy
  image:
    name: "artifactory.statnett.no/datascience-docker-local/sonar-scanner:latest"
  script:
    - sonar-scanner

publish_toolbox_to_artifactory:
  stage: deploy
  only:
    - tags
  script:
    - publish-to-artifactory $CI_PROJECT_NAME

pages:
  stage: deploy
  variables:
    ARTIFACTORY: "https://artifactory.statnett.no/artifactory/datascience-generic-local/sphinx"
    LIBRARIES: "python numpy pandas"
  only:
    - tags
  script:
    - for library in ${LIBRARIES}; do wget -nv -O docs/source/${library}.inv ${ARTIFACTORY}/${library}/objects.inv; done
    - tox -e sphinx
  artifacts:
    paths:
      - public
