image:
  name: "gitlab-docker.ci.statnett.no/abot/opf:latest"

stages:
  - tests
  - deploy

run_tests:
  stage: tests
  tags:
    - dind
  script:
    - tox -e pytest
  artifacts:
    paths:
      - coverage.xml
    expire_in: 1 day

sonar_update:
  stage: deploy
  image:
    name: "artifactory.statnett.no/datascience-docker-local/sonar-scanner:latest"
  tags:
    - dind
  when:
    always
  script:
    - sonar-scanner

publish_toolbox_to_artifactory:
  stage: deploy
  tags:
    - dind
  only:
    - tags
  script:
    - publish-to-artifactory $CI_PROJECT_NAME

pages:
  stage: deploy
  only:
    - tags
  script:
    - tox -e sphinx
  artifacts:
    paths:
      - public
