---

include:
  - project: 'stas/gitlab-ci/python-build'
    ref: v0
    file: 'publish-python.yml'

variables:
  PYTHON_VERSIONS: "/(3.7)|(3.8)/"
  PYTHON_PUBLISH_VERSION: "3.8"
  PKG_NAME: "cimsparql"
