prefix cim:<${cim}>
prefix SN:<${SN}>

# Create a load group
insert data {
    graph <http://cimsparql/xml-adpator/EQ-modifications> {
        _:b0 a cim:NonConformLoadGroup;
            cim:IdentifiedObject.name "created-group";
            SN:NonConformLoadGroup.ScheduleResource _:b1 .
        _:b1 SN:ScheduleResource.marketCode "created-load-resource-mcode"
    }
}
