PREFIX cim:<${cim}>
PREFIX SN:<${SN}>

INSERT
INSERT

INSERT
INSERT

INSERT
INSERT {
  GRAPH <http://cimsparql/xml-adpator/EQ-modifications> {
    _:b0 a SN:GeneratingUnit ; cim:IdentifiedObject.name "GeneratingUnit" .
    ?machine cim:SynchronousMachine.GeneratingUnit _:b0 .
    _:b0 SN:GeneratingUnit.ScheduleResource _:b1 .
    _:b1 SN:ScheduleResource.marketCode "market0001"
  }
}
WHERE {
  ?machine a cim:SynchronousMachine
  FILTER NOT EXISTS {
    ?machine cim:SynchronousMachine.GeneratingUnit ?unit
  }
}
