PREFIX cim: <${cim}>

INSERT

INSERT

INSERT

INSERT

INSERT
INSERT {
  GRAPH <http://cimsparql/xml-adpator/SV-modifications> {
    _:b0 cim:SvInjection.TopologicalNode ?tp_node ; a cim:SvInjection ; cim:SvInjection.pInjection 0.0 .
  }
}
WHERE {
  ?tp_node a cim:TopologicalNode .
  FILTER NOT EXISTS {
    ?s cim:SvInjection.TopologicalNode ?tp_node .
  }
}
