PREFIX cim: <${cim}>

INSERT

INSERT

INSERT

INSERT

INSERT
INSERT {
  GRAPH <http://cimsparql/xml-adpator/SV-modifications> {
    _:b0 a cim:SvPowerFlow ; cim:SvPowerFlow.Terminal ?terminal ; cim:SvPowerFlow.p "0.0" .
  }
}
WHERE {
  ?terminal a cim:Terminal .
  FILTER NOT EXISTS {
    ?s cim:SvPowerFlow.Terminal ?terminal .
  }
}
