PREFIX cim: <${cim}>
PREFIX SN: <${SN}>

INSERT {
  GRAPH <http://cimsparql/xml-adpator/EQ-modifications> {
    _:b0 a SN:GeneratingUnit ;
         cim:IdentifiedObject.name "GeneratingUnit" .
    ?machine cim:SynchronousMachine.GeneratingUnit _:b0 .
  }
}
WHERE {
  ?machine a cim:SynchronousMachine .
  FILTER NOT EXISTS {
    ?machine cim:SynchronousMachine.GeneratingUnit ?unit .
  }
}
