PREFIX cim:<${cim}>
PREFIX SN:<${SN}>
# Assign all loads that does not have a load group to the newly created load group

INSERT
INSERT INSERT INSERT INSERT INSERT {
  GRAPH <http://cimsparql/xml-adpator/EQ-modifications> {
    ?load cim:NonConformLoad.LoadGroup ?created_group
  }
}
WHERE {
  ?load a cim:EnergyConsumer .
  ?created_group cim:IdentifiedObject.name "created-group" .
  FILTER NOT EXISTS {
    ?load cim:NonConformLoad.LoadGroup ?group
  }
}
