PREFIX cim: <${cim}>
PREFIX SN: <${SN}>

INSERT
INSERT

INSERT
INSERT

INSERT
INSERT {
  GRAPH <http://cimsparql/xml-adpator/EQ-modifications> {
    ?equipment SN:Equipment.networkAnalysisEnable true .
  }
}
WHERE {
  ?terminal cim:Terminal.ConductingEquipment ?equipment .
}
