# Name: Add MRID
PREFIX cim: <${cim}>
INSERT {
  GRAPH ${g} {?s cim:IdentifiedObject.mRID ?mrid}}
WHERE {
  graph ${g} {?s a $ { rdf_type}} filter (not exists {?s cim:IdentifiedObject.mRID ?mrid})
  bind
  (str(?s) as ?mrid)
}
