# Name: Coordinates
PREFIX cim: <${cim}>
SELECT ?mrid ?x ?y ?epsg (STR(?resource_type) AS ?rdf_type) WHERE {
  ?s cim:PositionPoint.Location ?location ;
     cim:PositionPoint.sequenceNumber ?nr ;
     cim:PositionPoint.xPosition ?x ;
     cim:PositionPoint.yPosition ?y .
  ?location cim:Location.PowerSystemResources ?resource ;
            cim:Location.CoordinateSystem/cim:CoordinateSystem.crsUrn ?co .
  VALUES ?resource_type { cim:Substation cim:ACLineSegment }
  ?resource a ?resource_type ;
            cim:IdentifiedObject.mRID ?mrid .
  BIND (STRAFTER(?co,'EPSG::') AS ?epsg)
  BIND (CONCAT(STR(?mrid), STR(?nr)) AS ?sequence)
}
ORDER BY (?sequece)
