# Name: Market dates
PREFIX cim: <${cim}>
PREFIX SN: <${SN}>
select  ?mrid ?name ?activation_date
where {
  ?_set a SN:MarketDefinitionSet;
        cim:IdentifiedObject.mRID ?mrid;
        cim:IdentifiedObject.name ?name;
        SN:MarketDefinitionSet.activationDate ?activation_date
}
