# Name: Power flow
PREFIX cim:<${cim}>
SELECT ?mrid ?p ?q ?in_service WHERE {
  ?_s a cim:SvPowerFlow ;
      cim:SvPowerFlow.Terminal ?terminal ;
      cim:SvPowerFlow.p ?p ;
      cim:SvPowerFlow.q ?q .
  ?_eq_subject <http://entsoe.eu/CIM/EquipmentCore/3/1> ?eq_repo .
  SERVICE ?eq_repo {
    ?terminal cim:IdentifiedObject.mRID ?mrid .
  }
  OPTIONAL {
    ?terminal cim:Terminal.ConductingEquipment/^cim:SvStatus.ConductingEquipment/cim:SvStatus.inService ?_in_service
  }
  BIND (COALESCE(?_in_service, True) AS ?in_service)
}
