# Name: Regions
PREFIX cim: <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX SN: <http://www.statnett.no/CIM-schema-cim15-extension#>
SELECT ?mrid ?region ?short_name ?name ?alias_name ?region_name WHERE {
  ?subGeoRegion a cim:SubGeographicalRegion ;
                cim:IdentifiedObject.mRID ?mrid ;
                cim:IdentifiedObject.name ?name ;
                cim:SubGeographicalRegion.Region ?subgeoreg .
  OPTIONAL {
    ?subGeoRegion SN:IdentifiedObject.shortName ?short_name
  } .
  OPTIONAL {
    ?subGeoRegion cim:IdentifiedObject.aliasName ?alias_name
  } .
  ?subgeoreg cim:IdentifiedObject.name ?region .
  OPTIONAL {
    ?subgeoreg cim:IdentifiedObject.aliasName ?region_name
  }
}
