# Name: Station group code and names
PREFIX cim: <${cim}>
PREFIX SN: <${SN}>
SELECT ?station_group ?name ?alias_name WHERE {
  # SN is not made optional here because then there is no filtering left.
  # TODO: Is ScheduleResource available in a another namespace?
  ?s SN:ScheduleResource.marketCode ?station_group ;
     cim:IdentifiedObject.name ?name ;
  OPTIONAL {
    ?s cim:IdentifiedObject.aliasName ?alias_name
  }
}
