# Name: Substation voltage level
PREFIX cim:<${cim}>
select  ?container ?substation ?v
where {
  ?volt_level a cim:VoltageLevel;
              cim:IdentifiedObject.mRID ?container;
              cim:VoltageLevel.BaseVoltage/cim:BaseVoltage.nominalVoltage ?v;
              cim:VoltageLevel.Substation ?_substation .
  { select  (max(?volt) as ?v) ?_substation
    where {
      ?volt_level a cim:VoltageLevel;
                  cim:VoltageLevel.BaseVoltage/cim:BaseVoltage.nominalVoltage ?volt;
                  cim:VoltageLevel.Substation ?_substation .
    } group by ?_substation
  } .
  ?_substation cim:IdentifiedObject.mRID ?substation
}
