# Name: Substation voltage level
PREFIX cim:<${cim}>
SELECT ?container ?substation ?v WHERE {
  ?volt_level a cim:VoltageLevel ;
              cim:IdentifiedObject.mRID ?container ;
              cim:VoltageLevel.BaseVoltage/cim:BaseVoltage.nominalVoltage ?v ;
              cim:VoltageLevel.Substation ?_substation .
  {
    SELECT (MAX(?volt) AS ?v) ?_substation WHERE {
      ?volt_level a cim:VoltageLevel ;
                  cim:VoltageLevel.BaseVoltage/cim:BaseVoltage.nominalVoltage ?volt ;
                  cim:VoltageLevel.Substation ?_substation .
    }
    GROUP BY ?_substation
  } .
  ?_substation cim:IdentifiedObject.mRID ?substation
}
