# Name: Transformer Windings
PREFIX cim: <http://iec.ch/TC57/2013/CIM-schema-cim16#>
SELECT ?mrid ?end_number ?w_mrid WHERE {
  ?power_transformer a cim:PowerTransformer ;
                     cim:IdentifiedObject.mRID ?mrid .
  ?winding cim:IdentifiedObject.mRID ?w_mrid ;
           cim:PowerTransformerEnd.PowerTransformer ?power_transformer ;
           cim:TransformerEnd.endNumber ?end_number
}
