# Name: Type mapper
PREFIX rdf:<${rdf}>
PREFIX rdfs:<${rdfs}>
PREFIX cims:<${cims}>
SELECT DISTINCT ?sparql_type ?range WHERE {
  {
    ?sparql_type ^rdfs:domain/cims:dataType ?range .
    ?range cims:stereotype "Primitive"
  }
  UNION {
    ?sparql_type ^rdfs:domain/cims:dataType ?_dtype .
    ?_dtype cims:stereotype "CIMDatatype" .
    ?_dtype_value rdfs:domain ?_dtype ;
                  rdfs:label "value"@en ;
                  cims:dataType ?range
  }
}
