# Name: Type mapper
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cims: <http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#>
SELECT DISTINCT ?sparql_type ?range WHERE {
  {
    ?sparql_type ^rdfs:domain/cims:dataType ?range .
    ?range cims:stereotype "Primitive"
  }
  UNION {
    ?sparql_type ^rdfs:domain/cims:dataType ?_dtype .
    ?_dtype cims:stereotype "CIMDatatype" .
    ?_dtype_value rdfs:domain ?_dtype ;
                  rdfs:label "value"@en ;
                  cims:dataType ?range
  }
}
