# Name: Wind generating units
PREFIX cim: <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX SN: <http://www.statnett.no/CIM-schema-cim15-extension#>
SELECT ?mrid ?name ?market_code ?station_group ?min_p ?max_p ?plant_mrid WHERE {
  ?wind_gen_unit a cim:WindGeneratingUnit ;
                 cim:IdentifiedObject.mRID ?mrid ;
                 cim:IdentifiedObject.name ?name ;
                 cim:GeneratingUnit.maxOperatingP ?max_p ;
                 cim:GeneratingUnit.minOperatingP ?min_p .
  OPTIONAL {
    ?wind_gen_unit SN:WindGeneratingUnit.WindPowerPlant/cim:IdentifiedObject.mRID ?plant_mrid ;
                   SN:GeneratingUnit.marketCode ?market_code ;
                   SN:GeneratingUnit.ScheduleResource/SN:ScheduleResource.marketCode ?station_group .
  }
  OPTIONAL {
    ?wind_gen_unit SN:Equipment.networkAnalysisEnable ?_network_analysis
  }
  FILTER (?network_analysis)
  BIND (COALESCE(?_network_analysis, True) AS ?network_analysis)
}
