# Name: Transformer branches loss

PREFIX cim: <${cim}>
PREFIX SN: <${SN}>
PREFIX xsd: <${xsd}>

SELECT ?mrid (sum(xsd:double(str(?sv_p))) / sum(?in_service) AS ?ploss_2)
WHERE {
  ?terminal cim:ACDCTerminal.connected ?connected .
  OPTIONAL {
    ?terminal ^cim:SvPowerFlow.Terminal/cim:SvPowerFlow.p ?_sv_p .
  }
  OPTIONAL {
    ?winding ^cim:SvStatus.ConductingEquipment/cim:SvStatus.inService ?_in_service .
  }
  ?_eq_subject <http://entsoe.eu/CIM/EquipmentCore/3/1> ?eq_repo .
  SERVICE ?eq_repo {
    # Extract mRID and area for each power transformer
    ?winding cim:PowerTransformerEnd.PowerTransformer ?p_transformer ;
             cim:TransformerEnd.Terminal ?terminal .
    ?p_transformer cim:IdentifiedObject.mRID ?mrid ;
                   cim:Equipment.EquipmentContainer/cim:Substation.Region/cim:SubGeographicalRegion.Region/cim:IdentifiedObject.name ?area .
    FILTER regex(?area, '.*')
    OPTIONAL {
      ?p_transformer SN:Equipment.networkAnalysisEnable ?_network_analysis .
    }
  }
  BIND (IF(COALESCE(?_in_service, ?connected), 1, 0) AS ?in_service)
  BIND (COALESCE(?_sv_p, "0.0"^^xsd:double) AS ?sv_p)
  BIND (COALESCE(?_network_analysis, true) AS ?network_analysis)
  FILTER (?network_analysis = true)
}
GROUP BY ?mrid
