# Name: Windings
PREFIX cim: <${cim}>
PREFIX SN: <${SN}>
PREFIX xsd: <${xsd}>

select ?p_transformer (sum(?_count) as ?count) (max(?_name) as ?name) (sum(?in_service) as ?nr_on) (sum(xsd:double(str(?sv_p))) as ?p)
where
{
  optional {{?winding ^cim:SvStatus.ConductingEquipment/cim:SvStatus.inService ?_in_service .} .
  optional {?terminal cim:ACDCTerminal.connected ?_connected .}
  optional {?terminal ^cim:SvPowerFlow.Terminal/cim:SvPowerFlow.p ?_sv_p  .}

  ?_eq_subject <http://entsoe.eu/CIM/EquipmentCore/3/1> ?eq_repo .
  service ?eq_repo {
    ?winding cim:PowerTransformerEnd.PowerTransformer ?p_transformer;
            cim:TransformerEnd.Terminal ?terminal .
    ?p_transformer cim:IdentifiedObject.name ?_name .
  }
  bind(coalesce(?_connected, 1) as ?connected)
  bind(if(coalesce(?_in_service, ?connected), 1, 0) as ?in_service) .
  bind(coalesce(?_sv_p, xsd:double(0.0)) as ?sv_p)
  bind(1 as ?_count)
}
group by ?p_transformer
