# Name: Converters
PREFIX cim:<${cim}>
PREFIX xsd:<${xsd}>
PREFIX SN:<${SN}>
PREFIX ALG:<${ALG}>
select ?mrid ?name ?alias ?p ?q ?substation_mrid ?status ?node ?connectivity_node ?controller ?controller_factor
where {

  {
    select * where {
      ?_eq_subject <http://entsoe.eu/CIM/EquipmentCore/3/1> ?eq_repo .
      service ?eq_repo {
        # Extract mrid, name, substation and optionally aliasName of the converter
        ?converter cim:IdentifiedObject.mRID ?mrid;
                  cim:IdentifiedObject.name ?name;
            ALG:VoltageSourceConverter.DCPole|ALG:DCConverter.DCPole ?pole.
        ?pole ALG:DCPole.DCController/cim:IdentifiedObject.mRID ?controller;
              ALG:DCPole.participationFactor ?controller_factor;

        optional {?converter cim:IdentifiedObject.aliasName ?alias .}
        # Extract properties for the terminals for the converter
        ?terminal cim:Terminal.ConductingEquipment ?converter;
                  cim:Terminal.ConnectivityNode ?con_node;
                  cim:Terminal.sequenceNumber|cim:ACDCTerminal.sequenceNumber 1 .
        ?con_node cim:IdentifiedObject.mRID ?connectivity_node ;
          cim:ConnectivityNode.ConnectivityNodeContainer/cim:VoltageLevel.Substation ?substation .
        ?substation cim:IdentifiedObject.mRID ?substation_mrid;
          cim:Substation.Region/cim:SubGeographicalRegion.Region/cim:IdentifiedObject.name ?area .
        optional {?converter SN:Equipment.networkAnalysisEnable ?_analysis_enabled .}
        filter regex(?area, '${region}')
        bind(coalesce(?_analysis_enabled, True) as ?analysis_enabled)
        filter(?analysis_enabled)
      }
    }
  }

  # Extract active and reactive power for the converter
  ?converter cim:ACDCConverter.p ?p;
             cim:ACDCConverter.q ?q .

  optional {?converter ^cim:SvStatus.ConductingEquipment/cim:SvStatus.inService ?in_service .}

  # Extract connected and optionally the mrid for the topological node associated with the terminal
  ?terminal cim:ACDCTerminal.connected ?connected .

  {
    ?con_node cim:ConnectivityNode.TopologicalNode ?topological_node .
  } union {
    filter not exists {?con_node cim:ConnectivityNode.TopologicalNode ?topological_node}
    ?terminal cim:Terminal.TopologicalNode ?topological_node .
  }
  ?topological_node cim:IdentifiedObject.mRID ?node .

  bind(coalesce(?in_service, ?connected) as ?status)
}
