# Name: Coordinates
PREFIX cim: <${cim}>
select ?mrid ?x ?y ?epsg ?rdf_type
where {
  ?s cim:PositionPoint.Location ?location;
     cim:PositionPoint.sequenceNumber ?nr;
     cim:PositionPoint.xPosition ?x;
     cim:PositionPoint.yPosition ?y.
  ?location cim:Location.PowerSystemResources ?_mrid;
            cim:Location.CoordinateSystem/cim:CoordinateSystem.crsUrn ?co.
  ?_mrid a ?_rdf_type;
         cim:IdentifiedObject.mRID ?mrid.
  bind(strafter(?co, 'EPSG::') as ?epsg)
  bind(concat(str(?mrid), str(?nr)) as ?sequence)
  bind(str(?_rdf_type) as ?rdf_type)
} order by (?sequece)
