# Name: Disconnected
PREFIX cim:<${cim}>
select ?mrid where
{
  {
    ?mrid a cim:Disconnector;
          cim:Switch.open True .
  } union {
    ?mrid a cim:Terminal;
          cim:Terminal.connected|cim:ACDCTerminal.connected False .

  }
}
