# Name: Power flow
PREFIX cim:<${cim}>
select  ?mrid ?p ?q ?in_service
where {
  ?_s a cim:SvPowerFlow;
      cim:SvPowerFlow.Terminal ?terminal;
      cim:SvPowerFlow.p ?p;
      cim:SvPowerFlow.q ?q .
  ?_eq_subject <http://entsoe.eu/CIM/EquipmentCore/3/1> ?eq_repo .
  service ?eq_repo {
    ?terminal cim:IdentifiedObject.mRID ?mrid .
  }
  optional {?terminal cim:Terminal.ConductingEquipment/^cim:SvStatus.ConductingEquipment/cim:SvStatus.inService ?_in_service}
  bind(coalesce(?_in_service, True) as ?in_service)
}
