# Name: Protective Action
PREFIX cim: <${cim}>
PREFIX alg: <${ALG}>
select ?mrid ?equipment ?name ?type
where
{
  ?rpact (alg:ProtectiveActionEquipment.Equipment|alg:ProtectiveActionAdjustmentAC.ConductingEquipment|alg:ProtectiveActionAdjustmentDCController.DCController)/cim:IdentifiedObject.mRID ?equipment;
         cim:IdentifiedObject.mRID ?mrid;
         cim:IdentifiedObject.name ?name;
         a ?type .
}
