# Name: RAS Equipment
PREFIX cim: <${cim}>
PREFIX icim: <${icim}>
select ?mrid ?equipment_mrid ?name
where
{
  ?rpact (icim:ProtectiveActionEquipment.Equipment|icim:ProtectiveActionAdjustment.ConductingEquipment)/cim:IdentifiedObject.mRID ?equipment_mrid;
         cim:IdentifiedObject.mRID ?mrid;
         cim:IdentifiedObject.name ?name .
}
