# Name: Station group code and names
PREFIX cim: <${cim}>
PREFIX pti: <${pti}>
select ?station_group ?name ?alias_name where {
  ?s pti:ScheduleResource.marketCode ?station_group;
     cim:IdentifiedObject.name ?name.
  optional{?s cim:IdentifiedObject.aliasName ?alias_name}
}
