# Name: Winding transformer angle
PREFIX cim: <${cim}>
PREFIX xsd: <${xsd}>
select ?mrid ?angle
where {
  ?tap_changer cim:TapChanger.step ?ssh_position .
  optional{ ?tap_changer ^cim:SvTapStep.TapChanger/cim:SvTapStep.position ?sv_position } .

  ?_eq_subject <http://entsoe.eu/CIM/EquipmentCore/3/1> ?eq_repo .
  service ?eq_repo {
    ?tap_changer cim:PhaseTapChangerLinear.stepPhaseShiftIncrement ?inc;
                cim:TapChanger.neutralStep ?neutralstep;
                ^cim:TransformerEnd.PhaseTapChanger/cim:IdentifiedObject.mRID ?mrid .
  }

  bind(coalesce(?sv_position, ?ssh_position) as ?position)
  bind((xsd:double(str(?position)) - xsd:double(str(?neutralstep))) * xsd:double(str(?inc)) as ?angle)
}
