PREFIX rdf:<${rdf}>
PREFIX cim:<${cim}>
PREFIX SN:<${SN}>
select  ?mrid ?name ?station_group ?market_code ?min_p ?max_p ?plant_mrid
where {
  ?_mrid rdf:type cim:WindGeneratingUnit;
         cim:IdentifiedObject.mRID ?mrid;
         cim:IdentifiedObject.name ?name;
         cim:GeneratingUnit.maxOperatingP ?max_p;
         cim:GeneratingUnit.minOperatingP ?min_p .
  optional{
    ?_mrid SN:WindGeneratingUnit.WindPowerPlant/cim:IdentifiedObject.mRID ?plant_mrid;
           SN:GeneratingUnit.marketCode ?market_code;
           SN:GeneratingUnit.ScheduleResource/SN:ScheduleResource.marketCode ?station_group .
  }
  optional {?_mrid SN:Equipment.networkAnalysisEnable ?_network_analysis}
  filter(?network_analysis)
  bind(coalesce(?_network_analysis, True) as ?network_analysis)
}
