---
name: poetry

on:
  schedule:
    - cron: "0 9 * * 1"  # Mondays at 09:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and configure Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.6.1
      - uses: fredrikaverpil/poetry-update@v1.2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          branch: poetry-update
          add-paths: |
            poetry.lock
          commit-message: "Update poetry dependencies"
          title: "Update poetry dependencies"
          body: |

            ### Updated dependencies:

            ```bash
            ${{ env.POETRY_UPDATED }}
            ```

            ### Outdated dependencies _before_ PR:

            ```bash
            ${{ env.POETRY_OUTDATED_BEFORE }}
            ```

            ### Outdated dependencies _after_ PR:

            ```bash
            ${{ env.POETRY_OUTDATED_AFTER }}
            ```

            _Note: there may be dependencies in the table above which were not updated as part of this PR.
            The reason is they require manual updating due to the way they are pinned._
