
name: Semantic release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 24.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
